name: Build and Upload DSC MOF

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write

jobs:
  build-and-upload:
    runs-on: windows-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install PowerShell DSC Module
      shell: pwsh
      run: |
        Install-Module -Name PSDesiredStateConfiguration -Force -SkipPublisherCheck

    - name: Compile DSC Configuration
      shell: pwsh
      run: |
        .\PoweShell\nginx.ps1

    - name: Azure Login via Entra ID
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Upload MOF to Azure Storage
      shell: pwsh
      run: |
        $storageAccountName = "githubrepobackupstorage"
        $containerName = "dscconfigs"
        $blobName = "InstallNginx.mof"
        $localFilePath = ".\PowerShell\localhost.mof"

        # Pobierz Storage Context z Entra ID
        $storageContext = New-AzStorageContext -StorageAccountName $storageAccountName -UseConnectedAccount

        # Przesłanie pliku MOF do Storage Account
        Set-AzStorageBlobContent -File $localFilePath -Container $containerName -Blob $blobName -Context $storageContext -Force

    - name: Create and Assign Azure Policy for DSC
      shell: pwsh
      run: |
        $policyScript = ".\PowerShell\policy.ps1"
        pwsh -File $policyScript

